import { StyleSheet, Platform } from 'react-native';
import {
  SCREEN_WIDTH,
  SCREEN_HEIGHT,
  PROGRESS_BAR_PAD,
  PROGRESS_BAR_BOTTOM,
  PROGRESS_BAR_TOUCH_SLOP,
  PROGRESS_BAR_HEIGHT,
} from './constants';
import { spacing } from '../../theme/tokens';

export const videoFeedStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#000' },
  pressed: { opacity: 0.85 },

  cell: {
    justifyContent: 'center',
    alignItems: 'center',
    width: SCREEN_WIDTH,
    height: SCREEN_HEIGHT,
  },
  cover: {
    ...StyleSheet.absoluteFillObject,
    width: SCREEN_WIDTH,
    height: SCREEN_HEIGHT,
  },
  video: {
    ...StyleSheet.absoluteFillObject,
    width: SCREEN_WIDTH,
    height: SCREEN_HEIGHT,
  },
  coverOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.12)',
  },
  playIconWrap: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
  },

  progressBarWrap: {
    position: 'absolute',
    left: PROGRESS_BAR_PAD,
    right: PROGRESS_BAR_PAD,
    bottom: PROGRESS_BAR_BOTTOM,
    height: PROGRESS_BAR_TOUCH_SLOP,
    justifyContent: 'center',
    zIndex: 10,
  },
  progressBarTrack: {
    height: PROGRESS_BAR_HEIGHT,
    backgroundColor: 'rgba(255,255,255,0.35)',
    borderRadius: 2,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: 'rgba(255,255,255,0.95)',
    borderRadius: 2,
  },

  loadFailedOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 15,
  },
  loadFailedCard: {
    paddingVertical: 16,
    paddingHorizontal: 28,
    borderRadius: 12,
    backgroundColor: 'rgba(0,0,0,0.75)',
    alignItems: 'center',
    minWidth: 160,
  },
  loadFailedTitle: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 6,
  },
  loadFailedHint: {
    color: 'rgba(255,255,255,0.8)',
    fontSize: 14,
    fontWeight: '500',
  },

  sideBar: {
    position: 'absolute',
    right: spacing.lg,
    alignItems: 'center',
    gap: 20,
  },
  avatarWrap: { alignItems: 'center' },
  avatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
    borderWidth: 2,
    borderColor: '#fff',
  },
  followBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#fe2c55',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: -14,
  },
  followLabel: { color: 'rgba(255,255,255,0.9)', fontSize: 12, fontWeight: '700', marginTop: 4 },
  actionCol: { alignItems: 'center' },
  actionCount: { color: 'rgba(255,255,255,0.75)', fontSize: 13, fontWeight: '800', marginTop: 4 },
  actionLabel: { color: 'rgba(255,255,255,0.75)', fontSize: 12, fontWeight: '700', marginTop: 4 },

  infoBar: { position: 'absolute', maxWidth: SCREEN_WIDTH * 0.65 },
  userRow: {
    marginBottom: 10,
  },
  username: { color: '#fff', fontSize: 17, fontWeight: '800' },
  description: { fontSize: 15, lineHeight: 22, marginTop: 0 },
  descriptionText: { color: 'rgba(255,255,255,0.95)', fontWeight: '500' },
  tag: { color: '#ffd93d', fontWeight: '700' },

  topBar: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
  },
  topBarLeft: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  topBarSpacer: { flex: 1 },
  homeBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 20,
    backgroundColor: 'rgba(0,0,0,0.35)',
  },
  homeBtnText: { color: '#fff', fontSize: 14, fontWeight: '800' },
  mallEntry: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 20,
    backgroundColor: 'rgba(0,0,0,0.35)',
  },
  mallEntryText: { color: '#fff', fontSize: 14, fontWeight: '800' },
  settingsBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0,0,0,0.35)',
    alignItems: 'center',
    justifyContent: 'center',
  },

  settingsOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.4)' },
  settingsSheet: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '70%',
    overflow: 'hidden',
  },
  settingsSheetBlur: {
    ...StyleSheet.absoluteFillObject,
  },
  settingsSheetGlassOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(255,255,255,0.35)',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderColor: 'rgba(255,255,255,0.5)',
  },
  settingsSheetInner: {
    paddingHorizontal: spacing.lg,
  },
  settingsSheetHandle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#e2e8f0',
    alignSelf: 'center',
    marginTop: 12,
    marginBottom: 8,
  },
  settingsSheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.lg,
  },
  settingsSheetTitle: { fontSize: 18, fontWeight: '800', color: '#0f172a' },
  settingsSheetClose: { padding: 8 },
  settingsSheetContent: { paddingBottom: spacing.md },
  settingsSection: {
    marginBottom: 24,
  },
  settingsSectionTitle: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  settingsSectionTitleWithChips: {
    marginBottom: 12,
  },
  settingsSectionLabel: { fontSize: 15, fontWeight: '700', color: '#334155' },
  settingsActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 0,
  },
  settingsActionRowTappable: {
    paddingHorizontal: 16,
    borderRadius: 12,
    backgroundColor: '#f1f5f9',
  },
  speedChips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  speedChip: {
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 20,
    backgroundColor: '#f1f5f9',
  },
  speedChipActive: { backgroundColor: '#0f172a' },
  speedChipText: { fontSize: 14, fontWeight: '700', color: '#64748b' },
  speedChipTextActive: { color: '#fff' },
  qualityChips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  qualityChip: {
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 20,
    backgroundColor: '#f1f5f9',
  },
  qualityChipActive: { backgroundColor: '#0f172a' },
  qualityChipText: { fontSize: 14, fontWeight: '700', color: '#64748b' },
  qualityChipTextActive: { color: '#fff' },
  settingsActionBtnPressed: { opacity: 0.8 },
});
